name: kubernetes
image: mcp/kubernetes
type: server
meta:
  category: devops
  tags:
    - kubernetes
    - devops
about:
  title: Kubernetes
  description: Connect to a Kubernetes cluster and manage it
  icon: https://avatars.githubusercontent.com/u/13629408?s=200&v=4
source:
  project: https://github.com/Flux159/mcp-server-kubernetes
  commit: 1166816382e3e1a7ad56581997eb289a6a6513aa
run:
  volumes:
    - "{{kubernetes.config_path}}:/home/appuser/.kube/config"
config:
  description: Configure the location of the host Kubernetes file
  parameters:
    type: object
    properties:
      config_path:
        description: the path to the host .kube/config
        type: string
    required:
      - config_path
